name: Deploy GCP Function

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v2.1.0
        with:
          name: gcp_alert
          entry_point: gcp_alert_handler
          runtime: python311
          region: us-west1
          env_vars: |
            DISCORD_CRITICAL_WEBHOOK=${{ secrets.DISCORD_CRITICAL_WEBHOOK }},
            DISCORD_WARNING_WEBHOOK=${{ secrets.DISCORD_WARNING_WEBHOOK }}
          source_dir: .
          allow_unauthenticated: true
